rvm:
  - 2.1.2

before_install: gem update --remote bundler

before_script:
  - "bundle install"

script:
  - "bundle exec rspec"

notifications:
  webhooks: https://ci.neighbor.ly/projects/421aaf06-fc95-41a4-9677-701f9c809fc6/status
